"""Movie SQL, Neo4j, and pgvector tools."""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any

from langchain_core.tools import tool
from neo4j import GraphDatabase
from sqlalchemy import create_engine, event, text
from sqlalchemy.engine import Engine

from rag_agent.constants import get_movie_vector_table
from rag_agent.database.connections import (
    get_movie_sql_database_url,
    get_movie_vector_database_url,
)
from rag_agent.llm import get_embeddings
from rag_agent.movie_agent.models import MovieRecord

logger = logging.getLogger(__name__)


class SQLQueryLogger:
    """Small SQLAlchemy query logger for dynamic SQL execution."""

    def __init__(self) -> None:
        self.queries: list[str] = []

    def log_query(self, statement: str) -> None:
        self.queries.append(statement)
        logger.info("SQL query: %s", statement)


query_logger = SQLQueryLogger()


@event.listens_for(Engine, "before_cursor_execute")
def receive_before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    """Capture SQL statements before execution."""
    query_logger.log_query(statement)


def _is_read_only_query(query: str) -> bool:
    lowered = query.strip().lower()
    return lowered.startswith("select") or lowered.startswith("with")


CAMEL_CASE_SQL_IDENTIFIERS = {
    "titleType",
    "primaryTitle",
    "originalTitle",
    "isAdult",
    "startYear",
    "endYear",
    "runtimeMinutes",
    "primaryName",
    "birthYear",
    "deathYear",
    "primaryProfession",
    "averageRating",
    "numVotes",
}


def normalize_movie_sql_identifiers(query: str) -> str:
    """Quote known camelCase PostgreSQL identifiers generated by the LLM.

    Supabase/Postgres preserves these columns only when they are double quoted.
    LLMs often emit tc.startYear or mr.averageRating; Postgres folds those to
    lowercase and raises undefined-column errors.
    """
    normalized = query
    for identifier in sorted(CAMEL_CASE_SQL_IDENTIFIERS, key=len, reverse=True):
        normalized = re.sub(
            rf'(?<!")\b{re.escape(identifier)}\b(?!")',
            f'"{identifier}"',
            normalized,
        )
    return normalized


def _format_rows(rows: list[Any], columns: list[str]) -> str:
    result_lines = ["Query Results", "=" * 60]
    if not rows:
        result_lines.append("Query executed successfully. No rows returned.")
        return "\n".join(result_lines)
    header = " | ".join(columns)
    result_lines.extend([header, "-" * len(header)])
    for row in rows:
        result_lines.append(" | ".join(str(value) if value is not None else "NULL" for value in row))
    result_lines.append("")
    result_lines.append(f"Total rows: {len(rows)}")
    return "\n".join(result_lines)


@tool
def execute_movie_sql_query(query: str) -> str:
    """Execute a read-only SQL query against the movie SQL Supabase database."""
    if not query or not query.strip():
        return "Error: Empty SQL query provided"
    if not _is_read_only_query(query):
        return "Error: Only read-only SELECT/WITH SQL queries are allowed"
    try:
        query = normalize_movie_sql_identifiers(query)
        timeout = int(os.getenv("DB_CONNECT_TIMEOUT_SECONDS", "10"))
        engine = create_engine(get_movie_sql_database_url(), connect_args={"connect_timeout": timeout})
        with engine.connect() as conn:
            result = conn.execute(text(query))
            rows = result.fetchall()
            columns = list(result.keys())
        return _format_rows(rows, columns)
    except Exception as exc:
        return f"Error executing SQL query: {exc}"


@tool
def execute_movie_graph_query(query: str) -> str:
    """Execute a read-only Neo4j Cypher query against the movie graph."""
    if not query or not query.strip():
        return "Error: Empty Cypher query provided"
    if not query.strip().lower().startswith(("match", "with", "call")):
        return "Error: Only read-oriented Cypher queries are allowed"

    import os

    uri = os.getenv("NEO4J_URL")
    username = os.getenv("NEO4J_USERNAME")
    password = os.getenv("NEO4J_PASSWORD")
    database = os.getenv("NEO4J_DATABASE")
    if not all([uri, username, password]):
        return "Error: NEO4J_URL, NEO4J_USERNAME and NEO4J_PASSWORD are required"

    try:
        driver = GraphDatabase.driver(uri, auth=(username, password))
        with driver.session(database=database) as session:
            records = [record.data() for record in session.run(query)]
        driver.close()
        if not records:
            return "Query Results\n============================================================\nQuery executed successfully. No results returned."
        return (
            "Query Results\n"
            "============================================================\n"
            f"{json.dumps(records, ensure_ascii=False, indent=2)}\n\n"
            f"Total results: {len(records)}"
        )
    except Exception as exc:
        return f"Error executing Cypher query: {exc}"


def _chunk_text(text_value: str, chunk_size: int = 1800, overlap: int = 200) -> list[str]:
    if len(text_value) <= chunk_size:
        return [text_value]
    chunks: list[str] = []
    start = 0
    while start < len(text_value):
        end = start + chunk_size
        chunks.append(text_value[start:end])
        start = max(end - overlap, end)
    return chunks


class MovieVectorService:
    """pgvector service for the custom movie_plot_embeddings table."""

    def __init__(self, table_name: str | None = None) -> None:
        self.table_name = table_name or get_movie_vector_table()
        self.connection = get_movie_vector_database_url()
        self.embeddings = get_embeddings()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", self.table_name):
            raise ValueError(f"Unsafe vector table name: {self.table_name}")

    def _engine(self):
        timeout = int(os.getenv("DB_CONNECT_TIMEOUT_SECONDS", "10"))
        return create_engine(self.connection, connect_args={"connect_timeout": timeout})

    def _columns(self) -> set[str]:
        with self._engine().connect() as conn:
            rows = conn.execute(
                text(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema = 'public' AND table_name = :table_name"
                ),
                {"table_name": self.table_name},
            ).all()
        return {row[0] for row in rows}

    @staticmethod
    def _vector_literal(embedding: list[float]) -> str:
        return "[" + ",".join(str(float(value)) for value in embedding) + "]"

    @staticmethod
    def _content_column(columns: set[str]) -> str:
        if "content" in columns:
            return "content"
        if "plot" in columns:
            return "plot"
        raise RuntimeError("Vector table is missing a text column. Expected one of: content, plot")

    @staticmethod
    def _embedding_column(columns: set[str]) -> str:
        if "embedding" in columns:
            return "embedding"
        if "plot_embedding" in columns:
            return "plot_embedding"
        raise RuntimeError("Vector table is missing an embedding column. Expected one of: embedding, plot_embedding")

    def add_movies(self, movies_data: list[dict[str, Any]]) -> dict[str, Any]:
        """Embed and store movie records."""
        rows: list[dict[str, Any]] = []
        columns = self._columns()
        has_metadata = "metadata" in columns
        content_column = self._content_column(columns)
        embedding_column = self._embedding_column(columns)
        title_column = "title" if "title" in columns else None
        for payload in movies_data:
            movie = MovieRecord.model_validate(payload)
            content = movie.vector_content()
            chunks = _chunk_text(content)
            for idx, chunk in enumerate(chunks):
                metadata = {
                    "movie_id": movie.movie_id,
                    "primaryTitle": movie.primaryTitle,
                    "genres": movie.genres,
                    "startYear": movie.startYear,
                    "chunk_index": idx,
                    **movie.metadata,
                }
                rows.append(
                    {
                        "movie_id": movie.movie_id,
                        "title": movie.primaryTitle or movie.originalTitle or movie.movie_id,
                        "content": chunk,
                        "metadata": json.dumps(metadata),
                        "embedding": self._vector_literal(self.embeddings.embed_query(chunk)),
                    }
                )
        if rows:
            if content_column == "plot" and embedding_column == "plot_embedding" and title_column:
                insert_sql = text(
                    f"INSERT INTO {self.table_name} (movie_id, title, plot, plot_embedding) "
                    "VALUES (:movie_id, :title, :content, CAST(:embedding AS vector))"
                )
            elif has_metadata:
                insert_sql = text(
                    f"INSERT INTO {self.table_name} (movie_id, {content_column}, metadata, {embedding_column}) "
                    "VALUES (:movie_id, :content, CAST(:metadata AS jsonb), CAST(:embedding AS vector))"
                )
            else:
                insert_sql = text(
                    f"INSERT INTO {self.table_name} (movie_id, {content_column}, {embedding_column}) "
                    "VALUES (:movie_id, :content, CAST(:embedding AS vector))"
                )
            with self._engine().begin() as conn:
                conn.execute(insert_sql, rows)
        return {"processed_count": len(rows), "movie_count": len(movies_data)}

    def search(self, query: str, top_k: int = 5) -> list[dict[str, Any]]:
        """Search similar movie chunks."""
        columns = self._columns()
        if "movie_id" not in columns:
            raise RuntimeError(f"Vector table {self.table_name} is missing required column: movie_id")
        content_column = self._content_column(columns)
        embedding_column = self._embedding_column(columns)
        title_expr = "title" if "title" in columns else "NULL AS title"
        metadata_expr = "metadata" if "metadata" in columns else "'{}'::jsonb AS metadata"
        embedding = self._vector_literal(self.embeddings.embed_query(query))
        sql = text(
            f"""
            SELECT
                movie_id,
                {title_expr},
                {content_column} AS content,
                {metadata_expr},
                {embedding_column} <=> CAST(:embedding AS vector) AS distance
            FROM {self.table_name}
            WHERE {embedding_column} IS NOT NULL
            ORDER BY {embedding_column} <=> CAST(:embedding AS vector)
            LIMIT :limit
            """
        )
        with self._engine().connect() as conn:
            rows = conn.execute(sql, {"embedding": embedding, "limit": top_k}).mappings().all()
        return [
            {
                "content": row["content"],
                "metadata": {
                    **dict(row["metadata"] or {}),
                    "primaryTitle": row["title"],
                    "title": row["title"],
                },
                "movie_id": row["movie_id"],
                "score": float(row["distance"]) if row["distance"] is not None else None,
            }
            for row in rows
        ]


_vector_service: MovieVectorService | None = None


def get_movie_vector_service() -> MovieVectorService:
    """Return a singleton movie vector service."""
    global _vector_service
    if _vector_service is None:
        _vector_service = MovieVectorService()
    return _vector_service


def format_context_from_movies(results: list[dict[str, Any]]) -> str:
    """Format vector results as compact prompt context."""
    if not results:
        return "No similar movie context found."
    lines: list[str] = []
    for idx, result in enumerate(results, start=1):
        metadata = result.get("metadata", {})
        title = metadata.get("primaryTitle") or result.get("movie_id") or f"Movie {idx}"
        lines.append(
            f"[{idx}] {title}\n"
            f"movie_id: {metadata.get('movie_id', result.get('movie_id', ''))}\n"
            f"genres: {metadata.get('genres', '')}\n"
            f"year: {metadata.get('startYear', '')}\n"
            f"score: {result.get('score')}\n"
            f"content: {result.get('content', '')}"
        )
    return "\n\n".join(lines)
